# Generated by Django 4.1.2 on 2022-10-25 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
